# Generated by Django 6.0.2 on 2026-02-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='VIS Service Website', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('header_cta_text', models.CharField(default='Contact Us', max_length=50)),
                ('header_cta_url', models.CharField(default='/contact', max_length=200)),
                ('footer_note', models.CharField(blank=True, default='© All rights reserved.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
