# Generated by Django 6.0.2 on 2026-02-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_whychooseussection_whychooseusitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseusitem',
            name='icon',
        ),
        migrations.AddField(
            model_name='whychooseusitem',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Example: bi-people, bi-award, bi-graph-up', max_length=50),
        ),
    ]
